# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: auth for google
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Auth docker stuff
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: setup Chrome
        uses: browser-actions/setup-chrome@v1
#        with:
#          chrome-version: beta

      - name: check Chrome version
        run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - name: Build with Maven
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run:
          mvn -B verify com.google.cloud.tools:jib-maven-plugin:3.3.2:build -Djib.to.image=europe-west3-docker.pkg.dev/$GOOGLE_PROJECT/essensplanung/essensplanung:test --file pom.xml -P production
